### ISSUE TITLE
Not working in node 0.12.7

### ISSUE THREAD

**Issue by simonfan** [lukaaash/sftp-ws#1]
I have tried to run the module in an node v0.12.7 and all tests failed.
It seems that the problem is in lines 195-196 `sftp-packet.ts`

```
if ((<any>Buffer)._charsWritten != charLength) //WEB: // removed
   throw new Error("Not enough space in the buffer");
```

I have set up a docker container with node v0.10.40 and it works perfectly there.

I think https://github.com/joyent/node/commit/526c54c9#commitcomment-1143045 might prove somewhat useful.

**Comment by lukaaash** [comment]
Thanks! Looks like node devs [removed `_charsWritten`](https://github.com/joyent/node/commit/ccda6bb3ac99ee46508860385128f47a3d5547e5) because it was "never read from" (which seems obvious if it was intended to be used by third-party code), thus making it _impossible_ to determine whether the preceding `write` call properly wrote all the string characters... Fortunately, I already had a replacement function in the web-based version. Using that with node as well solves the issue. The current version should be [compatible with node v0.12.x](https://github.com/lukaaash/sftp-ws/commit/3c1d57a8b5098da6a17bf9932e2ee23c2a0ce549).

**Comment by simonfan** [comment]
Lukaaash, thanks for solving the problem.

But there is still another problem when running in node v0.12. In 0.10 all tests pass, but in 0.12 those with "no-path" apparently throw different errors.

```
Connection accepted.
    ✓ flags
    ✓ callback(fail)
    ✓ realpath('.')
    1) realpath(no-path)
    ✓ realpath(path)
    2) mkdir(no-path)
    ✓ mkdir(path)
    3) rmdir(no-path)
    ✓ rmdir(path)
    4) opendir(no-path)
    ✓ opendir(path)/readdir/close (109ms)
    5) rename(no-path, path2)
    6) rename(path1, no-path)
    ✓ rename(path1, path2)
    7) unlink(no-path)
    ✓ unlink(path)
    8) open(no-path, 'r+')
    ✓ open(path, 'r+')/read/close
    ✓ open(no-path, 'w+')/write/close
    ✓ read(no-handle)
    ✓ write(no-handle)
    ✓ close(no-handle)
    ✓ fstat(no-handle)
    9) stat(no-path)
    ✓ stat(path)
    10) lstat(no-path)
    ✓ lstat(path)
    ✓ fstat(closed-handle)
    ✓ fstat(handle)
    11) setstat(no-path)
    ✓ setstat(path)
    ✓ open(path)/fsetstat


  32 passing (336ms)
  11 failing

  1) Basic Tests realpath(no-path):

      AssertionError: Unexpected error code: EFAILURE
      + expected - actual

      -EFAILURE
      +ENOENT

      at error (tests/core-tests.js:62:16)
      at Client.<anonymous> (tests/core-tests.js:126:55)
      at finish (lib/util.js:57:26)
      at SftpClientCore.checkResponse (lib/sftp-client.js:414:17)
      at SftpClientCore.parsePath (lib/sftp-client.js:441:19)
      at SftpClientCore._process (lib/sftp-client.js:139:32)
      at WebSocketChannel.onmessage (lib/sftp-client.js:534:22)
      at WebSocket.<anonymous> (lib/channel-ws.js:29:23)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)

  2) Basic Tests mkdir(no-path):

      AssertionError: Unexpected error code: EFAILURE
      + expected - actual

      -EFAILURE
      +ENOENT

      at error (tests/core-tests.js:62:16)
      at Client.<anonymous> (tests/core-tests.js:136:52)
      at finish (lib/util.js:57:26)
      at SftpClientCore.checkResponse (lib/sftp-client.js:414:17)
      at SftpClientCore.parseStatus (lib/sftp-client.js:423:19)
      at SftpClientCore._process (lib/sftp-client.js:139:32)
      at WebSocketChannel.onmessage (lib/sftp-client.js:534:22)
      at WebSocket.<anonymous> (lib/channel-ws.js:29:23)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)

  3) Basic Tests rmdir(no-path):

      AssertionError: Unexpected error code: EFAILURE
      + expected - actual

      -EFAILURE
      +ENOENT

      at error (tests/core-tests.js:62:16)
      at Client.<anonymous> (tests/core-tests.js:148:52)
      at finish (lib/util.js:57:26)
      at SftpClientCore.checkResponse (lib/sftp-client.js:414:17)
      at SftpClientCore.parseStatus (lib/sftp-client.js:423:19)
      at SftpClientCore._process (lib/sftp-client.js:139:32)
      at WebSocketChannel.onmessage (lib/sftp-client.js:534:22)
      at WebSocket.<anonymous> (lib/channel-ws.js:29:23)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)

  4) Basic Tests opendir(no-path):

      AssertionError: Unexpected error code: EFAILURE
      + expected - actual

      -EFAILURE
      +ENOENT

      at error (tests/core-tests.js:62:16)
      at Client.<anonymous> (tests/core-tests.js:161:62)
      at finish (lib/util.js:57:26)
      at SftpClientCore.checkResponse (lib/sftp-client.js:414:17)
      at SftpClientCore.parseHandle (lib/sftp-client.js:435:19)
      at SftpClientCore._process (lib/sftp-client.js:139:32)
      at WebSocketChannel.onmessage (lib/sftp-client.js:534:22)
      at WebSocket.<anonymous> (lib/channel-ws.js:29:23)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)

  5) Basic Tests rename(no-path, path2):

      AssertionError: Unexpected error code: EFAILURE
      + expected - actual

      -EFAILURE
      +ENOENT

      at error (tests/core-tests.js:62:16)
      at Client.<anonymous> (tests/core-tests.js:195:61)
      at finish (lib/util.js:57:26)
      at SftpClientCore.checkResponse (lib/sftp-client.js:414:17)
      at SftpClientCore.parseStatus (lib/sftp-client.js:423:19)
      at SftpClientCore._process (lib/sftp-client.js:139:32)
      at WebSocketChannel.onmessage (lib/sftp-client.js:534:22)
      at WebSocket.<anonymous> (lib/channel-ws.js:29:23)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)

  6) Basic Tests rename(path1, no-path):

      AssertionError: Unexpected error code: EFAILURE
      + expected - actual

      -EFAILURE
      +ENOENT

      at error (tests/core-tests.js:62:16)
      at Client.<anonymous> (tests/core-tests.js:202:61)
      at finish (lib/util.js:57:26)
      at SftpClientCore.checkResponse (lib/sftp-client.js:414:17)
      at SftpClientCore.parseStatus (lib/sftp-client.js:423:19)
      at SftpClientCore._process (lib/sftp-client.js:139:32)
      at WebSocketChannel.onmessage (lib/sftp-client.js:534:22)
      at WebSocket.<anonymous> (lib/channel-ws.js:29:23)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)

  7) Basic Tests unlink(no-path):

      AssertionError: Unexpected error code: EFAILURE
      + expected - actual

      -EFAILURE
      +ENOENT

      at error (tests/core-tests.js:62:16)
      at Client.<anonymous> (tests/core-tests.js:219:53)
      at finish (lib/util.js:57:26)
      at SftpClientCore.checkResponse (lib/sftp-client.js:414:17)
      at SftpClientCore.parseStatus (lib/sftp-client.js:423:19)
      at SftpClientCore._process (lib/sftp-client.js:139:32)
      at WebSocketChannel.onmessage (lib/sftp-client.js:534:22)
      at WebSocket.<anonymous> (lib/channel-ws.js:29:23)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)

  8) Basic Tests open(no-path, 'r+'):

      AssertionError: Unexpected error code: EFAILURE
      + expected - actual

      -EFAILURE
      +ENOENT

      at error (tests/core-tests.js:62:16)
      at Client.<anonymous> (tests/core-tests.js:232:65)
      at finish (lib/util.js:57:26)
      at SftpClientCore.checkResponse (lib/sftp-client.js:414:17)
      at SftpClientCore.parseHandle (lib/sftp-client.js:435:19)
      at SftpClientCore._process (lib/sftp-client.js:139:32)
      at WebSocketChannel.onmessage (lib/sftp-client.js:534:22)
      at WebSocket.<anonymous> (lib/channel-ws.js:29:23)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)

  9) Basic Tests stat(no-path):

      AssertionError: Unexpected error code: EFAILURE
      + expected - actual

      -EFAILURE
      +ENOENT

      at error (tests/core-tests.js:62:16)
      at Client.<anonymous> (tests/core-tests.js:312:58)
      at finish (lib/util.js:57:26)
      at SftpClientCore.checkResponse (lib/sftp-client.js:414:17)
      at SftpClientCore.parseAttribs (lib/sftp-client.js:428:19)
      at SftpClientCore._process (lib/sftp-client.js:139:32)
      at WebSocketChannel.onmessage (lib/sftp-client.js:534:22)
      at WebSocket.<anonymous> (lib/channel-ws.js:29:23)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)

  10) Basic Tests lstat(no-path):

      AssertionError: Unexpected error code: EFAILURE
      + expected - actual

      -EFAILURE
      +ENOENT

      at error (tests/core-tests.js:62:16)
      at Client.<anonymous> (tests/core-tests.js:326:59)
      at finish (lib/util.js:57:26)
      at SftpClientCore.checkResponse (lib/sftp-client.js:414:17)
      at SftpClientCore.parseAttribs (lib/sftp-client.js:428:19)
      at SftpClientCore._process (lib/sftp-client.js:139:32)
      at WebSocketChannel.onmessage (lib/sftp-client.js:534:22)
      at WebSocket.<anonymous> (lib/channel-ws.js:29:23)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)

  11) Basic Tests setstat(no-path):

      AssertionError: Unexpected error code: EFAILURE
      + expected - actual

      -EFAILURE
      +ENOENT

      at error (tests/core-tests.js:62:16)
      at Client.<anonymous> (tests/core-tests.js:360:68)
      at finish (lib/util.js:57:26)
      at SftpClientCore.checkResponse (lib/sftp-client.js:414:17)
      at SftpClientCore.parseStatus (lib/sftp-client.js:423:19)
      at SftpClientCore._process (lib/sftp-client.js:139:32)
      at WebSocketChannel.onmessage (lib/sftp-client.js:534:22)
      at WebSocket.<anonymous> (lib/channel-ws.js:29:23)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)

```

**Comment by lukaaash** [comment]
Actually, the [node 0.12.x compatibility](https://github.com/lukaaash/sftp-ws/commit/3c1d57a8b5098da6a17bf9932e2ee23c2a0ce549) commit should fix that as well - it looks like node started reporting a different error code for ENOENT on Windows (see the change in `src/lib/sftp-server.ts` file).
Please make sure you are testing with the latest version, and if the tests still fail, let me know. The server-side at least needs a better debug logging to make it possible to easily tell what is going on.

**Comment by simonfan** [comment]
Lukaaash, 

The latest commit is this one, right?

```
commit 0b10883a36af55e46c2e04deb07851c8a3fe3ee5
Author: Lukas Pokorny <lukas@nuane.com>
Date:   Sun Aug 30 20:58:41 2015 +0200

Converted gulpfile.ts to gulpfile.js - needed for 'gulp' to work instantly
```

I've run the tests inside a docker container with node 0.12.7. 
Just tried again and same results :/

(and thanks for the gulpfile.js, before I had to run tsc and then gulp)

**Comment by lukaaash** [comment]
Found the issue! It turns out that node 0.12.x uses yet another errno for ENOENT on Linux... So that's three possible values now: https://github.com/lukaaash/sftp-ws/commit/b3f2e58242831b2cdb2a5759b8889a9d94ec38c5

Also added better server-side logging, it might be useful next time :-)
